### ISSUE TITLE
Unable to update deployment with the same name

### ISSUE THREAD

**Issue by andreisaikouski** [mdbootstrap/mdb-cli#50]
**Expected behavior**

Publishing with the same name would update the existing deployment.

**Actual behavior**

mdb-cli throws the following, requesting a new name:
```
Error The project name is already taken by one of your other projects. Please choose a different name.
```

**Context**

- mdb-cli version 3.4.0
- system: Mac BigSur v11.3

**Comment by catchmareck** [comment]
Try running `mdb publish --override` once - it should resolve the issue.

It's probably happening because of the change that we made to disallow creating projects with the same name. The `--override` flag should do the trick. Note that you only need to use it once - no need to add it every time.

**Comment by andreisaikouski** [comment]
Hi @catchmareck,
Thanks for the response.

This does not resolve the issue as running `mdb backend publish -p node12 -n project-name --override` throws:

```
   Error Could not publish: There were some errors.
```

Furthermore, subsequently running `mdb backend publish -p node12 -n project-name ` continues to throw the original error:

```
   Error The project name is already taken by one of your other projects. Please choose a different name.
```

Thanks
